from .tensormoead import TensorMOEAD
from .moead_foriloop import MOEAD1
from .p_moead import PMOEAD
from .moead_origin import MOEAD
from .hype_origin import HypE
from .tensorhype import TensorHypE
from .nsga2_origin import NSGA2Origin
from .tensornsga3 import TensorNSGA3
from .nsga3_origin import NSGA3
from .nsga3_origin import NSGA3Origin2
